---
title: "PPDx"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PPDx}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ppdx)
library(ggplot2)
```

### Analyze BAM

```{r eval=FALSE}
# Location of the BAM file
bam_location <- args[1]
# Location of the reference file
reference_location <- args[2]

# Calculate scores for the BAM file and the reference (for plotting).
samples <-
  ppdx::calculate_scores(bam_location, reference_location, include_reference = T)

sample_name <- basename(bam_location)


# Make plot nicer
main_theme <- ggplot2::theme_bw() +
  ggplot2::theme(
    panel.border = ggplot2::element_blank(),
    axis.line = ggplot2::element_line(),
    strip.background = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    legend.position = "none",
    axis.title.x = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_text(
      angle = 90,
      hjust = 1,
      vjust = 0.5
    )
  )

# Plot results
last_plot <- ggplot2::ggplot(samples, aes(x = focus,
                                          y = p)) +
  ggplot2::geom_point(
    data = samples %>% dplyr::filter(reference),
    aes(alpha = 0.5),
    color = "grey",
    shape = 16
  ) +
  ggplot2::geom_point(
    data = samples %>% dplyr::filter(!reference),
    color = "black",
    shape = 17
  ) +
  ggplot2::ylab("Probability of interest") +
  ggplot2::ggtitle(sample_name) +
  main_theme +
  ggplot2::scale_color_grey()

# Save plot
ggplot2::ggsave(paste0(sample_name, ".png"), last_plot)

# Save results
readr::write_tsv(path = paste0(sample_name, ".tsv"), x = reads_per_bin)
```

